-- Create tables for Projeto Sanfran 2027

-- 1. Profiles (linked to auth.users)
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Syllabus Progress (Stores checked items)
create table syllabus_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  item_id text not null,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, item_id)
);

-- 3. Books Progress (Stores status of readings)
create table books_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  book_id integer not null,
  status text not null, -- 'unread', 'reading', 'read', 'summarized'
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, book_id)
);

-- 4. Simulados (Stores exam scores)
create table simulados (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null,
  score integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Notes (Dashboard Notepad)
create table notes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS) policies to ensure users only see their own data

alter table profiles enable row level security;
alter table syllabus_progress enable row level security;
alter table books_progress enable row level security;
alter table simulados enable row level security;
alter table notes enable row level security;

-- Policies
create policy "Users can view their own profile" on profiles for select using (auth.uid() = id);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);

create policy "Users can manage their syllabus" on syllabus_progress for all using (auth.uid() = user_id);
create policy "Users can manage their books" on books_progress for all using (auth.uid() = user_id);
create policy "Users can manage their simulados" on simulados for all using (auth.uid() = user_id);
create policy "Users can manage their notes" on notes for all using (auth.uid() = user_id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
